config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  
  resources :users do
    resources :likes#, :except => [:new]
    resources :messages
  end

  post '/' => 'users#search'

  get '/apartments' => 'apartments#index'

  get '/results' => 'users#show'

  get '/login' => 'sessions#new'

  get '/logout' => 'sessions#destroy'

  post '/sessions' => 'sessions#create'

  get 'users/:user_id/congrats/:id' => 'likes#congrats', as: :users_id_congrats
  
  post 'users/:id/likes' => 'likes#create', as: :create_user_like

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :to, :class_name => :user
  belongs_to :from, :class_name => :user

  def self.messages(to_id, from_id)
    Message.where("to_id = ? AND from_id = ?", to_id, from_id)
  end

  def conversation_with(recipient_id)
    current_user_messages = Message.messages(self.id, recipient_id)
    recipient_messages = Message.messages(recipient_id, self.id)
    conversation = (current_user_messages + recipient_messages).sort_by(&:created_at)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def show
    @liker = User.find(params[:user_id])
    @likee = User.find(params[:id])
  end

  def create
    message = Message.new(:to_id => params[:likee_id], :from_id => params[:user_id], :content => params[:content])
    message.save
    redirect_to user_message_path(params[:user_id], params[:likee_id])
  end
end

app/views/messages/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%= root_path %>>
        <img id="timber-logo" alt="timber" src="<%= asset_path 'timber2.png' %>" style="height:35px;margin-top: -15px;">
      </a>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <% if session[:user_id] %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Matches", user_likes_path(User.find(session[:user_id])) %></li>
        <li><%= link_to "#{User.find(session[:user_id]).first_name}", user_path(User.find(session[:user_id])) %></li>
    <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/messages/show.html.erb
<%= render 'users/header' %>

  <div class="col-md-offset-4 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <img alt="Img 0872" src="<%= @likee.prof_img %>" width="250px" height "250">
      </div>
        <div class="caption">
          <p>
            <h2>Your conversation with <%= @likee.first_name %>:</h2>
          </p>  

          <!-- CHAT BOX -->
          <!-- outter div -->
          <div class="chat"> 
            <p>
              <% @liker.conversation_with(@likee.id).each do |message| %>
                <div style=width:100%;>
                <% if message.from_id == @liker.id%>
                  <div class="col-xs-9">
                    <div class="message-holder">
                      <div class="bubble you">
                        <%= message.content%>
                      </div>
                    </div>
                  </div>
                  <div class="col-xs-3">
                    <div class="image-holder">
                      <%= image_tag(@liker.prof_img, width: '100%', )%>
                    </div>
                  </div>
                <% else %>
                  <div class="col-xs-3">
                    <div class="image-holder">
                      <%= image_tag(@likee.prof_img, width: '100%')%>
                    </div>
                  </div>
                  <div class="col-xs-9">
                    <div class="message-holder">
                      <div class="bubble me">
                        <%= message.content%>
                      </div>
                    </div>
                  </div>
                <% end %>
                </div>
                <div class="clearfix"></div>
              <% end %>     
            </p>
          </div>
          
          <div class="submit-box">
            <%= form_tag(user_messages_path(@liker.id, :params => {:likee_id => @likee.id}), method: "post", rows: "1") do %>
              <div class = "col-xs-9">
                <%= text_area_tag(:content) %>
              </div>

              <div class ="col-xs-3">
                <%= submit_tag("Send") %>
              </div>
            <% end %>
            <div class="clearfix"></div>
          </div>

        </div>
      </div>
    </div>
  </div>