config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  
  resources :users do
    resources :likes#, :except => [:new]
    resources :messages
  end

  post '/' => 'users#search'

  get '/apartments' => 'apartments#index'

  get '/results' => 'users#show'

  get '/login' => 'sessions#new'

  get '/logout' => 'sessions#destroy'

  post '/sessions' => 'sessions#create'

  get 'users/:user_id/congrats/:id' => 'likes#congrats', as: :users_id_congrats
  
  post 'users/:id/likes' => 'likes#create', as: :create_user_like

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :liker, :class_name => :user
  belongs_to :likee, :class_name => :user

  def self.all_by_liker(liker_id)
    where(:liker_id => liker_id)
  end

  def self.has_a_match(like) #=> returns matching like, or nil if doesn't exist
    find_by("liker_id = ? AND likee_id = ?", like.likee_id, like.liker_id)
  end

  def self.create_match(user_id1, user_id2)
    l = Like.new(:liker_id => user_id1, :likee_id => user_id2)
    u = Like.new(:liker_id => user_id2, :likee_id => user_id1)
    l.save
    u.save
  end

  def self.reset_matches
    Like.destroy_all
    Dislike.destroy_all
    Like.create_match(7, 9)
    Like.create_match(7, 10)
    Like.create_match(14, 4)
  end
   
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def new #route name: new_user_like_path
    @liker = User.find(session[:user_id])
    price = session[:price]
    hood_id = session[:hood_id]

    if @liker.guest?
      users = @liker.potential_hosts(price, hood_id)
    else
      users = @liker.potential_guests(price)
    end
    if users.count == 0
      @error = true
    else
      @error = false
      @likee = users.first
      @likee.host? ? @apt = @likee.apartment : @asset = ""
    end
  end

  def create
    @liker = User.find(session[:user_id])
    
    if params[:likee_id]
      like = Like.new(:likee_id => params[:likee_id], :liker_id => @liker.id)
      like.save
    else
      dislike = Dislike.new(:dislikee_id => params[:dislikee_id], :disliker_id => @liker.id)
      dislike.save
    end

    if @liker.new_match?(params[:likee_id].to_i)     
      redirect_to users_id_congrats_path(@liker.id, params[:likee_id])
    else
      redirect_to new_user_like_path
    end
  end

  def index
    @user = User.find(session[:user_id])
    @matches = @user.matches
    @matches.count == 0 ? @error = true : @error = false
  end

  #show page of your match and messaging
  def show
    @likee_id = params[:likee_id]
    @liker_id = params[:user_id]
  end

  def congrats
    @likee = User.find(params[:id])
    @liker = User.find(params[:user_id])
  end


end

app/views/likes/_header.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%=root_path%>">
        <img id="timber-logo" alt="timber" src="<%= asset_path 'timber2.png' %>" style="height:35px;margin-top: -15px;">
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Matches", user_likes_path(User.find(session[:user_id])) %></li>
        <li><%= link_to "#{User.find(session[:user_id]).first_name}", user_path(User.find(session[:user_id])) %></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/likes/congrats.html.erb
<%= render 'likes/header' %>

<div style="background:black !important" class="jumbotron-j jumbo-inverse text-center">
    <div class="container-congrats"> 
      <img id="timber-logo" alt="timber" src="<%= asset_path 'timber2.png' %>"> 
      <h3>It's a match!<br>You and <%= @likee.first_name %> have liked each other.</h3>
      <br>
      <!-- picture of the matching couple -->
      <img width="100" height "100" src="<%= @liker.prof_img %>">
      <img width="100" height "100" src="<%= @likee.prof_img %>">

      <!-- Messages button -->
      <br><br>
      <a href="<%= user_message_path(@liker.id, @likee.id) %>" class="btn btn-danger" role="button">Message</a> 
      <!-- Continue searching button  -->
      <%= button_to "Keep Playing", "/users/#{@liker.id}/likes/new", :method => "get", class: "btn btn-default" %>
      <!-- show page button  -->
      <%= button_to "View Profile", "/users/#{@likee.id}", :method => "get", class: "btn btn-danger" %>
    </div>
</div>

app/views/likes/index.html.erb
<%= render 'likes/header' %>

<% if @error %>
  <h1><%= @user.first_name %>, you don't have any matches yet.</h1>
<% else %>
  <div class="col-md-offset-1">
    <h1><%= @user.first_name %>, here are all your matches.</h1>
    <div class="media">
      
        <% @matches.each do |match|%>
          <div class="panel panel-default panel-width">
            <div class="panel-body">
              <a class="media-left media-middle" href="/users/<%=match.id%>">
              <img width="150" height "150" src="<%= match.prof_img %>" class="img-thumbnail details">
              </a>
              <div class="media-body details>
                <h4 class="media-heading"><%=match.first_name%>, <%=match.age%></h4>
                <div class="decision-btn decision">
                <a href="<%= user_message_path(@user.id, match.id) %>" class="btn btn-danger" role="button">Message</a>  
                <a href="/users/<%= match.id %>" class="btn btn-default" role="button">View Profile</a>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/likes/new.html.erb
<html>
  <head>
    <title></title>
  </head>
  <body>

    <%= render 'likes/header' %>


    <% if @error %>
      <h1>There are no users based on that criteria. To find users, go back and adjust your search criteria.</h1>

    <% else %>      
    
        <div class="col-md-offset-4 col-md-4">
            <div class="panel panel-default">
              <div class="panel-heading center">
                <a href="<%= user_path(@likee.id) %>"><img alt="Img 0872" src="<%= @likee.prof_img %>" class="img-nice-square"></a>
              </div>
                <div class="caption">
                  <p>
                    <h2><%= @likee.first_name %>, <%= @likee.age %></h2>
                  </p>  
                  <p>

                    <%= button_to "/users/#{@liker.id}/likes", :method => "post", :params => {:dislikee_id => @likee.id}, class: "btn btn-danger decision-btn" do %>
                      <i class="fa fa-close"></i>
                    <% end %>

                  <%= button_to "/users/#{@liker.id}/likes", :method => "post", :params => {:likee_id => @likee.id}, class: "btn btn-default decision-btn" do %>
                      <i class="fa fa-heart"></i>
                    <% end %>
                    <div class="clearfix">
                    </div>
                  </p>
                </div>
              </div>
            </div>
          </div>

    
    <% end %>

  </body>
  </html>

app/views/likes/show.html.erb
<%= render 'likes/header' %>
<h1>You matched with <a href="<%= @likee.id %>"><%= @likee.name %></a>!</h1>

<!-- picture of soAndSo -->
<a href="<%= @likee.id %>"><img width="100" height "100" src="<%= @likee.prof_img %>"></a>

<!-- message box ... install ruby gem-->