config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  
  resources :users do
    resources :likes#, :except => [:new]
    resources :messages
  end

  post '/' => 'users#search'

  get '/apartments' => 'apartments#index'

  get '/results' => 'users#show'

  get '/login' => 'sessions#new'

  get '/logout' => 'sessions#destroy'

  post '/sessions' => 'sessions#create'

  get 'users/:user_id/congrats/:id' => 'likes#congrats', as: :users_id_congrats
  
  post 'users/:id/likes' => 'likes#create', as: :create_user_like

end

app/models/user.rb
class User < ActiveRecord::Base
  # # Include default devise modules. Others available are:
  # # :confirmable, :lockable, :timeoutable and :omniauthable
  # devise :database_authenticatable, :registerable,
  #        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :users

  has_one :apartment
  belongs_to :hood
  belongs_to :asset
  has_one :social_life
  has_many :likes, :foreign_key => 'liker_id'
  has_many :likes, :foreign_key => 'likee_id'
  has_many :dislikes, :foreign_key => 'disliker_id'
  has_many :dislikes, :foreign_key => 'dislikee_id' 
  has_many :messages, :foreign_key => 'from_id'
  has_many :messages, :foreign_key => 'to_id'


  def self.have_apts
    self.joins(:apartment)
  end

  def self.not_have_apts
    self.where.not(id: Apartment.select(:user_id))
  end

  def self.women_seeking_men
    self.where("gender = ? AND orientation = ? AND looking_for = ?", "female", "straight", "men")
  end

  def self.men_seeking_women
    self.where("gender = ? AND orientation = ? AND looking_for = ?", "male", "straight", "women")
  end

  def self.current_user
    self.find(session[:user_id])
  end

  def self.price_array
    price_array = (500..4000).step(500).to_a
    price_array = price_array.map do |price| 
      s = price.to_s
      dollar = "$#{s}"
      if s.length > 3
        dollar.insert(-4, ",")
      end
      [dollar, price]
    end
    price_array.insert(0, 'any price')
  end

  def self.length_of_stay_array
  [["any period", 0],["1 night", 1], ["1-2 weeks", 2], 
    ["1 month+", 3]]
  end

  def self.hood_array
    hood_array = Hood.all.map{|hood| [hood.name, hood.id]}
    hood_array.insert(0, 'any neighborhood')
  end

  def has_liked?
    Like.where(:liker_id => self.id).count == 0 ? false : true
  end

  def has_disliked?
    Dislike.where(:disliker_id => self.id).count == 0 ? false : true
  end

  def matches #=> returns array of users who you matched with you
    matches = []
    if self.has_liked?
      Like.all_by_liker(self.id).find_each do |like|
        if Like.has_a_match(like)
          matches << User.find(like.likee_id)
        end
      end
    end
    matches
  end


  def new_match?(likee_id) 
    new_match = self.matches.select {|user| user.id == likee_id}
    new_match.count > 0 ? true : false
  end

  def potential_guests(budget)
    if budget == 'any price'
      self.unviewed_users
    else
      self.unviewed_users.where("budget > ?", budget)
    end
  end

  def potential_hosts(price, hood_id)
    if price == 'any price' && hood_id == 'any neighborhood'
      self.unviewed_users
    elsif price == 'any_price' && hood_id != 'any neighborhood'
      self.unviewed_users.joins(:apartment).merge( Apartment.apts_by_hood(hood_id))
    elsif price != 'any_price' && hood_id == 'any neighborhood'
      self.unviewed_users.joins(:apartment).merge( Apartment.apts_by_price(price))
    else
      self.unviewed_users.joins(:apartment).merge( Apartment.apts_by_price_and_hood(price, hood_id))
    end
  end

  def unviewed_users #=> returns users
    users = self.filtered_users
    if self.has_liked?
      Like.where(:liker_id => self.id).find_each do |like|
        users = users.where.not(:id => like.likee_id)
      end
    end
    if self.has_disliked?
      Dislike.where(:disliker_id => self.id).find_each do |dislike|
        users = users.where.not(:id => dislike.dislikee_id)
      end
    end
    users
  end

  def filtered_users #=> returns the users that the current user is looking for
    if self.gender == "male" && self.orientation == "straight" && self.looking_for == "women"
      @users = User.women_seeking_men
    elsif self.gender == "female" && self.orientation == "straight" && self.looking_for == "men"
      @users = User.men_seeking_women
    else
      @users = "error"
    end
    self.host? ? @users.not_have_apts : @users.have_apts
  end

  def host?
    self.apartment ? true : false
  end

  def guest?
    self.apartment ? false : true
  end

  def has_new_match?
    
  end


  def conversation_with(recipient_id)
    current_user_messages = Message.messages(self.id, recipient_id)
    recipient_messages = Message.messages(recipient_id, self.id)
    conversation = (current_user_messages + recipient_messages).sort_by(&:created_at)
  end

  def authenticate(password)
    if self.password == password
      return true
    else
      return false
    end    
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @price_array = User.price_array
    @hood_array = User.hood_array
    @los_array = User.length_of_stay_array

    if session[:user_id] 
      @user_is_guest = User.find(session[:user_id]).guest? 
    else
      redirect_to login_path
    end
  end

  def search
    @user = User.find(session[:user_id])
    session[:price] = params[:apartment][:price]
    if @user.guest?
      session[:hood_id] = params[:apartment][:hood_id]
    else 
      session[:asset_id] = params[:asset][:asset_id]
    end

    redirect_to new_user_like_path(@user)
  end

  def create
    #making a post request with signup info from the NEW form
    @user = User.new

    if @user.save
      redirect_to('/results')
    else
      render :new
    end

  end

  def new
    #this route should show a form for new user signup
    @user = User.new
    @user.save
  end

  def edit
    #edit link from profile page
    @user = User.find(params[:id])
  end

  def show
    #profile page
    @user = User.find(params[:id])  
  end

  def update
    #post request send from edit route
  end

  def destroy  
  end



  def login
    @user = User.new #not a new user...
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'users/header' %>
<h1>Edit Your Profile</h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
<br><br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
<br><br>
  <%= f.label :age %>
  <%= f.text_field :age %>
<br><br>
age - M/F
<br><br>
  <%= f.label :orientation %>
  <%= f.text_field :orientation %>
<br><br>
  <%= f.label :looking_for %>
  <%= f.text_field :looking_for %>
<br><br>
  <%= f.label :prof_img %>
  <%= f.text_field :prof_img %>
<br><br>
  <%= f.label :password %>
  <%= f.password_field :password %>
<br><br>
<%= f.label :password %>
  <%= f.password_field :password %>
<br><br>
  <%= f.submit "Update", class: "btn btn-primary" %>
<% end %>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
</head>

<body background="http://c4.staticflickr.com/4/3840/14867493817_f7254e9846_h.jpg">
  <%= render 'users/header' %>
  
  <div style="background:black !important" class="jumbotron jumbo-inverse text-center">
    <div class="container"> 
      <img id="timber-logo" alt="timber" src="<%= asset_path 'timber2.png' %>"> 
      <h3>it's going down</h3>

      <%= form_tag("/", method: "post") do %>
        <%= label_tag(:price, "Price") %>
        <%= select(:apartment, :price, options_for_select(@price_array))%>
        <% if @user_is_guest %> 
          <%= label_tag(:hood_id, "Neighborhood") %>
          <%= select(:apartment, :hood_id, options_for_select(@hood_array)) %>
        <% else %>
          <%= label_tag(:asset_id, "Length of stay") %>
          <%= select(:asset, :asset_id, options_for_select(@los_array)) %> 
        <% end %>
        <br>
        <%= button_tag(type: "submit", class: "btn btn-default btn-lg") do %>
          search <i class="icon-repeat"></i>
        <% end %>
        <a class="btn btn-danger btn-lg" href="/users/new">sign up</a>
      <% end %>
    </div>
</div>

</body>
</html>

app/views/users/login.html.erb
<%= render 'users/header' %>
<h1>Login</h1>

<%= form_tag(sessions_path) do |f| %>
  <p>
  <%= label_tag(:email, "Email:") %>
  <%= text_field_tag(:email) %>
  </p>
  <p>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %>
  </p>

  <%= submit_tag("Log in", class: "btn btn-primary") %>
<% end %>
<h6>Don't have an account? <a href="/users/new">Sign up</a> </h6>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
<br><br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
<br><br>
  <%= f.label :age %>
  <%= f.text_field :age %>
<br><br>
age - M/F
<br><br>
  <%= f.label :orientation %>
  <%= f.text_field :orientation %>
<br><br>
  <%= f.label :looking_for %>
  <%= f.text_field :looking_for %>
<br><br>
  <%= f.label :prof_img %>
  <%= f.text_field :prof_img %>
<br><br>
  <%= f.label :password %>
  <%= f.password_field :password %>
<br><br>
  <%= f.submit "Sign up!", class: "btn btn-primary" %>
<% end %>

app/views/users/search.html.erb
You are looking for: <%= @gender %>

app/views/users/show.html.erb
<!-- Add in like functionality from the show page or at least have a back button -->

<%= render 'users/header' %>
<!-- <a href="/users/<%#=@user.id%>/edit">Edit</a> -->


<div class="row">

  <div class="col-md-offset-4 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <img alt="Img 0872" src="<%= @user.prof_img %>" class="img-nice-square" style>
      </div>
    </div>
  </div>

  
    <div class="col-md-offset-4 col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading center">
          <img alt="Img 0872" src="<%= @user.apt_img %>" class="img-nice-square">
        </div>
          <div class="caption">
            <p>
              <h2><%= @user.first_name %>, <%= @user.age %></h2>
              <!-- ul>
                <li><%#= @user.age %></li>
              </ul> -->
            </p> 
          <% if @user.host? %> 
            <p>
              <h4><%= @user.apartment.hood.name %></h4>
              <ul>
                <li>Street: <%= @user.apartment.no_number_address %></li>
                <li>Bedroom count: <%= @user.apartment.br_count %></li>
                <li>Price: <%= @user.apartment.dollarize_price %>/month</li>
              </ul>
            </p>
          <% end %>
          <% if @user.id != session[:user_id] %>
            <p>
              <%= button_to "/users/#{@user.id}/likes", :method => "post", :params => {:dislikee_id => @user.id}, class: "btn btn-danger decision-btn" do %>
                    <i class="fa fa-close"></i>
              <% end %>

              <%= button_to "/users/#{@user.id}/likes", :method => "post", :params => {:likee_id => @user.id}, class: "btn btn-default decision-btn" do %>
                <i class="fa fa-heart"></i>
              <% end %>
              <div class="clearfix"></div>
            </p>
          <% end %>
          </div>
        </div>
      </div>
  </div>

  <!-- (/^\d+\s/,"") -->

app/views/users/update.html.erb
update.html.erb